"""followers

Revision ID: 77129a494b7f
Revises: 1640b6cce482
Create Date: 2020-12-30 10:48:45.685990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77129a494b7f'
down_revision = '1640b6cce482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
